### PR TITLE
Added Facebook Strategy

### PR DESCRIPTION
**Pull request by sportelance**
Still working on fine-tuning the strategy and tests. Uploading for others to reference.

### CODE REVIEW

**Review by BAlexanderNance — APPROVED** [review]
Looks good, had two remove to conflict issues but the code looks good.

**Review by alcheng005 — APPROVED** [review]
This is cool

**Review by BAlexanderNance — APPROVED** [review]
New additions look great!  Amazing work.

**Comment by BAlexanderNance** [comment]
Great work Sam!

**Pull request merged**
